### ISSUE TITLE
FATAL occured while opening videos in scripts/extract_optical_flow.sh

### ISSUE THREAD

**Issue by GBJim** [yjxiong/temporal-segment-networks#10]
Hi guys :)

I encountered a similar problem to #6,  the following are the error message.

2016-09-07 02:44:23,873 FATAL [default] Check failed: [video_stream.isOpened()] Cannot open video stream "/root/data/UCF-101/SalsaSpin/v_SalsaSpin_g22_c04.avi" for optical flow extraction.
2016-09-07 02:44:23,873 WARN  [default] Aborting application. Reason: Fatal log at [/root/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:15]

All the videos prompted the same error message.

The video path is correct, but it just can't open the video.
The openCV came from the TSN installation package, it should be okay.   
Any suggestion to solve this problem?

**Comment by yjxiong** [comment]
If the video path is surely correct, one remaining issue might be the OpenCV is compiled without VideoIO support. Please cd into the build folder of OpenCV `3rd-party/opencv-2.4.12/build/` and run the command `cmake ..`

In the output, please try to find the section about VideoIO. On my workstation, it shows something like

```
--   Video I/O:
--     DC1394 1.x:                  NO
--     DC1394 2.x:                  YES (ver 2.2.1)
--     FFMPEG:                      YES
--       codec:                     YES (ver 54.35.0)
--       format:                    YES (ver 54.20.4)
--       util:                      YES (ver 52.3.0)
--       swscale:                   YES (ver 2.1.1)
--       resample:                  NO
--       gentoo-style:              YES
```

**Comment by GBJim** [comment]
Thank you  for the quick response @yjxiong!

Just like you said, my openCV didn't support the Video I/O.
The problem is solved after I ran `apt-get install libopencv-dev` and the` cmake ..` command to re-install openCV

**Comment by 124399839** [comment]
@yjxiong ，The openCV came from the TSN installation package, it should be okay.
excute scripts/extract_optical_flow.sh ,the log as follows:

2018-07-24 18:44:43,119 FATAL [default] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
2018-07-24 18:44:43,119 WARN  [default] Aborting application. Reason: Fatal log at [/home/project/temporal-segment-networks/lib/dense_flow/include/easylogging++/src/easylogging++.h:5583]
2018-07-24 18:44:43,142 FATAL [default] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
2018-07-24 18:44:43,142 WARN  [default] Aborting application. Reason: Fatal log at [/home/project/temporal-segment-networks/lib/dense_flow/include/easylogging++/src/easylogging++.h:5583]
305 v_WritingOnBoard_g20_c05 done

Any suggestion to solve this problem?

**Comment by Ivy-blooming** [comment]
> @yjxiong ，The openCV came from the TSN installation package, it should be okay.
> excute scripts/extract_optical_flow.sh ,the log as follows:
> 
> 2018-07-24 18:44:43,119 FATAL [default] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
> 2018-07-24 18:44:43,119 WARN [default] Aborting application. Reason: Fatal log at [/home/project/temporal-segment-networks/lib/dense_flow/include/easylogging++/src/easylogging++.h:5583]
> 2018-07-24 18:44:43,142 FATAL [default] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
> 2018-07-24 18:44:43,142 WARN [default] Aborting application. Reason: Fatal log at [/home/project/temporal-segment-networks/lib/dense_flow/include/easylogging++/src/easylogging++.h:5583]
> 305 v_WritingOnBoard_g20_c05 done
> 
> Any suggestion to solve this problem?

I meet the same problem as you,could you solve this problem and share with me how to solve it？

**Comment by liuglen** [comment]
@Ivy-blooming Have you solved the problem?

**Comment by niveditarahurkar** [comment]
@yjxiong @GBJim I am seeing the same issue. So I did install apt-get install libopencv-dev and did cmake .. But still see the same.

**Comment by niveditarahurkar** [comment]
I am trying to run -
scripts/extract_optical_flow.sh /home/nirahurk/temporal-segment-networks/src_folder/ /home/nirahurk/temporal-segment-networks/out_folder/ 1
 I have taken just 5 sample videos from UCF101 in my src_folder:
 v_SkateBoarding_g25_c01  v_SkateBoarding_g25_c02  v_SkateBoarding_g25_c03  v_SkateBoarding_g25_c04  v_SkateBoarding_g25_c05
I get the output:
 4 v_SkateBoarding_g25_c01 done
3 v_SkateBoarding_g25_c03 done and so on..
But my out_folder --> out_folder/v_SkateBoarding_g25_c01# is empty.

**Comment by nanhui69** [comment]
@124399839 @Ivy-blooming Have you solved that problems ? if you have done it ,how did you do it?

**Comment by Ivy-blooming** [comment]
I installed Dockers to solve this problem




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nanhui69"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月9日(星期一) 下午2:41
收件人:&nbsp;"yjxiong/temporal-segment-networks"<temporal-segment-networks@noreply.github.com&gt;;
抄送:&nbsp;"✨🍓"<1363837225@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjxiong/temporal-segment-networks] FATAL occured while opening videos in scripts/extract_optical_flow.sh (#10)




@124399839 @Ivy-blooming Have you solved that problems ? if you have done it ,how did you do it?

**Comment by Light--** [comment]
i still got this problem, but my video io seems ok?

```
--   Video I/O:
--     DC1394:                      YES (ver 2.2.4)
--     FFMPEG:                      YES
--       avcodec:                   YES (ver 58.54.100)
--       avformat:                  YES (ver 58.29.100)
--       avutil:                    YES (ver 56.31.100)
--       swscale:                   YES (ver 5.5.100)
--       avresample:                YES (ver 2.1.0)
--     GStreamer:                   
--       base:                      YES (ver 1.8.3)
--       video:                     YES (ver 1.8.3)
--       app:                       YES (ver 1.8.3)
--       riff:                      YES (ver 1.8.3)
--       pbutils:                   YES (ver 1.8.3)
--     libv4l/libv4l2:              NO
--     v4l/v4l2:                    NO
--     gPhoto2:                     YES

```

**Comment by blowing-wind** [comment]
我遇到了同样的问题，最后发现是磁盘空间满了。

**Comment by TitaniumOne** [comment]
@Light--  @niveditarahurkar @Ivy-blooming Hello, I met the same problem, have you solved it? Thank you!

**Comment by TitaniumOne** [comment]
> 
> I installed Dockers to solve this problem
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"nanhui69"<notifications@github.com&gt;; 发送时间:&nbsp;2019年9月9日(星期一) 下午2:41 收件人:&nbsp;"yjxiong/temporal-segment-networks"<temporal-segment-networks@noreply.github.com&gt;; 抄送:&nbsp;"✨🍓"<1363837225@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [yjxiong/temporal-segment-networks] FATAL occured while opening videos in scripts/extract_optical_flow.sh (#10) @124399839 @Ivy-blooming Have you solved that problems ? if you have done it ,how did you do it? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

I use the docker too, but it does not work.

**Comment by smj0411** [comment]
> @yjxiong ，The openCV came from the TSN installation package, it should be okay. excute scripts/extract_optical_flow.sh ,the log as follows:
> 
> 2018-07-24 18:44:43,119 FATAL [default] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal 2018-07-24 18:44:43,119 WARN [default] Aborting application. Reason: Fatal log at [/home/project/temporal-segment-networks/lib/dense_flow/include/easylogging++/src/easylogging++.h:5583] 2018-07-24 18:44:43,142 FATAL [default] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal 2018-07-24 18:44:43,142 WARN [default] Aborting application. Reason: Fatal log at [/home/project/temporal-segment-networks/lib/dense_flow/include/easylogging++/src/easylogging++.h:5583] 305 v_WritingOnBoard_g20_c05 done
> 
> Any suggestion to solve this problem?

I meet the same problem as you,could you solve this problem and share with me how to solve it？
